### ISSUE TITLE
Grouping of Rooms

### ISSUE THREAD

**Issue by theduke** [mirukana/mirage#168] opened 2021-01-04 21:53 UTC
Joining a lot of rooms can easily lead to big visibility problems for important/preferred channels and group chats.

Element tries to solve this (somewhat suboptimally, for now) by grouping rooms into public channels (Rooms), direct chats (People), manually pinned favorites and low priority channels.

It would be great if mirage had something similar. 

My ideal solution would be the ability manually create different groups , assign rooms/chats to those groups and show them in a sorted fashion in the sidebar.

Not sure how much of this is supported by the protocol though.

**Comment by mirukana** [comment] 2021-01-07 06:10
Duplicate of https://github.com/mirukana/mirage/issues/6 and https://github.com/mirukana/mirage/issues/71

**Closed by mirukana** 2021-01-07 06:10 UTC
Labels: enhancement
