### ISSUE TITLE
Error pasting image into Mirage

### ISSUE THREAD

**Issue by drudgesentinel** [mirukana/mirage#238] opened 2021-07-28 18:23 UTC
### Description

When I paste an image to send with Mirage, the image preview loads correctly. However, when I click 'send' a stack trace  is produced and the image never sends. Pasting the same image into other applications functions nominally.

### Your environment

- OS or distribution (e.g. Arch Linux, macOS 10.15, Windows 7...) OpenSUSE Tumbleweed Linux
- Architecture (e.g. x86 64bit) 64 bit
- For Linux users: your desktop environment or window manager (e.g. GNOME 3.34 Wayland, i3 4.17, etc) GNOME (Xorg)
- How did you install Mirage? (e.g. manual build, distribution repository, AppImage, Flatpak...) Flatpak
[mirage-error.txt](https://github.com/mirukana/mirage/files/6895603/mirage-error.txt)

### Steps to reproduce

1. Use right click => 'copy image'
2. Paste the image into Mirage

### Expected behavior

Image should send

### Actual behavior

'Unexpected error occured: Attribute Error'

```
AttributeError: @golden:demise.tv.send_clipboard_image.552c440a-a0b5-4e20-92e2-33eab596f6ce

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "qrc:/src/backend/utils.py", line 368, in _compress
    pil_image.save(buffer, fmt, optimize=optimize)
AttributeError: 'NoneType' object has no attribute 'save'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 91, in on_done
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 732, in send_clipboard_image
    await self.send_file(room_id, get_path, reply_to_event_id)
  File "qrc:/src/backend/matrix_client.py", line 753, in send_file
    await self._send_file(item_uuid, room_id, path, reply_to_event_id)
  File "qrc:/src/backend/matrix_client.py", line 778, in _send_file
    path             = Path(await path() if callable(path) else path)
  File "qrc:/src/backend/matrix_client.py", line 725, in get_path
    compressed = await utils.compress_image(image, optimize=False)
  File "qrc:/src/backend/utils.py", line 378, in compress_image
    COMPRESSION_POOL, _compress, image, fmt, optimize,
AttributeError: 'NoneType' object has no attribute 'save'

```

**Comment by MRAAGH** [comment] 2021-08-30 01:26
Duplicate of #229

**Comment by drudgesentinel** [comment] 2022-07-03 17:45
Closing because it's a duplicate

**Closed as not planned** 2022-07-03 17:45 UTC
Labels: bug
