### ISSUE TITLE
MembersSyncError: The room is encrypted and the members aren't fully synced.

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#54] opened 2020-06-17 16:36 UTC
### Description

When sending a message in an end-to-end encrypted room, getting the following error message every time. Do I need to do something to force a sync? Will this eventually sort out?:

```

Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 82, in on_done
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 454, in send_text
    await self._send_message(room_id, content, tx_id)
  File "qrc:/src/backend/matrix_client.py", line 769, in _send_message
    await self.room_send(
  File "/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 1480, in room_send
    message_type, content = self.encrypt(
  File "/usr/lib/python3.8/site-packages/nio/client/base_client.py", line 116, in inner
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/nio/client/base_client.py", line 1159, in encrypt
    raise MembersSyncError(
nio.exceptions.MembersSyncError: The room is encrypted and the members aren't fully synced.

```

### Your environment

- OS or distribution (e.g. Arch Linux, macOS 10.15, Windows 7...) 
Arch Linux
- Architecture (e.g. x86 64bit) 
64bit
- How did you install Mirage? 
`yay -S matrix-mirage`

### Steps to reproduce

1. login to my existing account
2. import my E2EE keys via file export from Riot
3. Say "hello" in an encrypted room

**Comment by BurnyBoi** [comment] 2020-06-17 17:38
Just tested on another existing account without importing a key file from Riot, and same result. Consistently getting this error about members not being synced.

**Comment by mirukana** [comment] 2020-06-18 02:00
I think the issue comes from [here](https://github.com/mirukana/matrix-nio/blob/mirage-issue-54/nio/client/async_client.py#L1455) in nio, where I added some prints. Can you install this branch, restart mirage and report what appears in your terminal then when you try to send a message?

```
git clone https://github.com/mirukana/matrix-nio
cd matrix-nio
git checkout origin/mirage-issue-54
pip3 install --user -U '.[e2e]'
```

**Comment by mirukana** [comment] 2020-06-19 02:43
I updated the branch to add more logging, make sure to paste all the lines (you missed the "members synced 2" in the previous post).

**Comment by ellietheoracle** [comment] 2020-06-30 08:37
ok, this is starting to happen in more encrypted rooms, and logging out and back in doesn't fix the issue which is really odd, and even though my other account doesn't show up in the encrypted roomlist, i can still send messages from that account into the room, but the icon and name are missing, until i re-open the room .

**Comment by mirukana** [comment] 2020-06-30 08:47
> I updated the branch to add more logging, make sure to paste all the lines (you missed the "members synced 2" in the previous post).

Can you do this then?

**Comment by ellietheoracle** [comment] 2020-07-01 02:44
one thing i've noticed with this error, is that my other account is always what's missing from the sidebar, it's never another room member, it can't be a coincidence so many times ?

**Comment by ellietheoracle** [comment] 2020-07-01 02:44
and if i send messages from the other account, and then close and re-open the room, sometimes the other account will show up, and then it lets me send messages .

**Comment by ellietheoracle** [comment] 2020-07-01 04:48
members_synced:  4 0 3
room_send: members synced: False
members_synced:  4 0 3
_handle_joined_members: members added:  2
room_send: members response: <class 'nio.responses.JoinedMembersResponse'>
members_synced:  4 0 3
room_send: members synced 2: False
members_synced:  4 0 3
X 23:47:29 | python: 
Traceback (most recent call last):
  File "qrc:/src/backend/qml_bridge.py", line 82, in on_done
    result = future.result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "qrc:/src/backend/matrix_client.py", line 455, in send_text
    await self._send_message(room_id, content, tx_id)
  File "qrc:/src/backend/matrix_client.py", line 770, in _send_message
    await self.room_send(
  File "/home/oracle/Documents/GitHub/matrix-nio/nio/client/async_client.py", line 1481, in room_send
    message_type, content = self.encrypt(
  File "/home/oracle/Documents/GitHub/matrix-nio/nio/client/base_client.py", line 114, in inner
    return fn(self, *args, **kwargs)
  File "/home/oracle/Documents/GitHub/matrix-nio/nio/client/base_client.py", line 1158, in encrypt
    raise MembersSyncError(
nio.exceptions.MembersSyncError: The room is encrypted and the members aren't fully synced.

**Comment by mirukana** [comment] 2020-07-01 05:07
How many joined members does this room contain, including yourself, with a fully loaded member list? 4?

**Comment by ellietheoracle** [comment] 2020-07-01 05:25
4, yes .

**Comment by FoundOne** [comment] 2020-07-27 03:44
I can confirm that it happens on Manjaro-arm (PineBook Pro) too. That's maybe the main thing which makes Mirage unusable for me. I still can read the messages from the encrypted rooms.

**Comment by mirukana** [comment] 2020-07-27 08:38
Can you still reproduce this after the dev branch commit d127ad9? 
You might need to install a special branch of matrix-nio for the test, see https://github.com/mirukana/mirage/issues/31#issuecomment-664110568

**Comment by FoundOne** [comment] 2020-07-27 14:42
It's much better, but it still happens for some encrypted rooms. It looks like it happens on some crowded ones, but that's just a speculation. I'm using the latest head on the dev branch.

**Comment by mirukana** [comment] 2020-07-27 19:59
I need more info on the room that fails, compare Mirage's member list with the one from a client that handles the room correctly (e.g. Element):

- Is there any member that shouldn't be here, e.g. members that already left or were kicked?
- Are there missing members? Did they join the room recently? 
- Any missing "x joined/left the room" events at the timeline's bottom?

If that helps, you can do this to get the number of loaded members in Mirage:
- Press F1 to open the debug console
- Type `ModelStore.get("@your_user_id:example.org", "!theRoomId:example.org", "members").count`. You can quickly copy the user and room ID by right clicking on your account and the room in the left panel.

**Comment by FoundOne** [comment] 2020-07-28 04:11
My guess about the user count is totally wrong. The number of users varies. The server I'm on, is quite new, so there are still no kicked/banned for now. It seems Mirage misses some invitations. I think it should show them, right? I saw it doing it. I'm not sure what happens to the invited users who go offline. I haven't looked into the code.

**Comment by theotheroracle** [comment] 2020-08-02 00:26
encrypted rooms do show invited user though ?

**Comment by FoundOne** [comment] 2020-08-02 11:29
It does not show all of them sometimes. There are some invitations missing. I looked at Element in the web browser. I guess I have to find a way to reproduce it.

**Comment by mirukana** [comment] 2020-08-28 16:21
Can you still reproduce this in 0.6.2? Make sure you have matrix-nio 0.15.1.

**Comment by theotheroracle** [comment] 2020-09-20 23:07
invites still don't show up in encrypted rooms, which is what causes the bug seemingly, but as of yet i haven't gotten a membersyncerror

**Comment by mirukana** [comment] 2020-11-05 11:53
The invite bug has been fixed in https://github.com/poljar/matrix-nio/commit/560a4a0bdeea96001546ac534241de52bb4b8abf

**Closed by mirukana** 2020-11-05 11:53 UTC
Labels: backend, bug
