### ISSUE TITLE
Error and timeout when quitting Mirage

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#211] opened 2021-04-12 00:53 UTC
### Description

When quitting Mirage, I sometimes get this error:
```
INFO:root:Setting clients offline...
ERROR:asyncio:Exception in callback SSLProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle SSLProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 477, in connection_made
    self._sslpipe = _SSLPipe(self._sslcontext,
  File "/usr/lib/python3.9/asyncio/sslproto.py", line 70, in __init__
    self._incoming = ssl.MemoryBIO()
ssl.SSLError: ('failed to allocate BIO',)
```
And then it waits for about 15 seconds without quitting, until finally it times out:
```
WARNING:root:@maze:sorunome.de timed out
```

This might be homeserver-specific and I haven't found a reliable way to reproduce it. But it's been happening to me every now and then ever since I've started using Mirage.

### Your environment
- Arch Linux 64-bit
- window manager: Awesome wm v4.3
- How did you install Mirage? manual build
- Qt 5.15.2
- Python 3.9.2

### Expected behavior

If possible, it would make more sense to immediately cancel this operation when there's an error, so I don't need to wait to get my shell back.

### Actual behavior

I need to wait for timeout, not even ctrl+C stops it. This is especially annoying while developing/testing.

**Comment by mirukana** [comment] 2021-04-12 04:52
Duplicate of #130 (see last comment)

**Closed by mirukana** 2021-04-12 04:52 UTC
Labels: bug
